# generated by Neptune Namespaces v3.x.x
# file: Art.Mat/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Mat'
.addModules
  Icons:          require './Icons'         
  StandardImport: require './StandardImport'
  TextPalette:    require './TextPalette'   
  TextStyles:     require './TextStyles'    
require './Lib'
require './Models'