# generated by Neptune Namespaces v3.x.x
# file: Art.Mat/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.Mat', class Mat extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Models/namespace'