# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Mat/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.Mat', class Mat extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
