# generated by Neptune Namespaces v3.x.x
# file: Art.Mat/Lib/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Lib'
.addModules
  Time: require './Time'